### ISSUE TITLE
extending the db object

### ISSUE THREAD

**Issue by substack** [cshum/level-transactions#2]
First, thanks for the fantastic module! I was just about to write something like this myself when I found this package.

The only part that feels a bit off to me is how this package extends the db object with a `db.transaction()` method similarly to [level-sublevel](https://www.npmjs.com/package/level-sublevel). I think a better model for providing functionality on top of leveldb is to pass in an ordinary levelup or leveldown instance to a function that returns a function or a new instance like how [subleveldown](https://www.npmjs.com/package/subleveldown) works:

``` js
var sub = require('subleveldown')
var db = level('db')
var test = sub(db, 'test') // test is a new prefixed levelup
```

The subleveldown approach works best across a vast ecosystem of packages like we have on npm since there might be many versions of a library in a dependency tree, and modifying a reference will affect functionality globally. This subverts semver and makes applications more fragile against library changes.

I propose a level-transactions api more similar to the subleveldown approach:

``` js
var db = level('./db')
var transaction = require('level-transactions');

var tx = transaction(db);
```

If you'd like I can send a pull request for this feature too. Thanks for the great module!

**Comment by cshum** [comment]
The original way of extending db object was kinda resemble the sublevel way of a level- plugin. I do agree the subleveldown's modular approach is better. Thanks for your feedback!
