### ISSUE TITLE
Range lock tx.createReadStream()

### ISSUE THREAD

**Issue by cshum** [cshum/level-transactions#3]
Range lock `tx.createReadStream()` is an essential but non-trivial feature to implement.

Things to consider:
* Need to snapshot the whole readStream range.
* Level of locking: global, prefix or ltgt based?

**Comment by delaneyj** [comment]
I would like this as well, my guess is ltgt based would give the most options.

**Comment by cshum** [comment]
Instead of range lock, `createReadStream` now performs implicit snapshot same as Leveldown, with isolated result set.
