### ISSUE TITLE
Key prefix of this.location?

### ISSUE THREAD

**Issue by alanshaw** [cshum/level-transactions#7]
I have code (read only from the db) that might work in the context of a transaction or it might not. In level-transactions v1 the db was interchangeable, but upgrading to v2 it seems that the keys automatically get prefixed with "./data" - the database directory. How can I stop this from happening?

**Comment by cshum** [comment]
Hey @alanshaw may you try 2.1.4 which attempts to fix this issue. Thanks.

**Comment by alanshaw** [comment]
Thanks! I'll take a look when I have a sec...
